Bridge DApp styling
schnoodledao/contracts pull request #12
Opened 2022-05-28 10:54 UTC by koteakhaladze

2022-05-28 13:22 UTC, NeoXtreem requested changes

2022-05-28 13:22 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/components/Bridge.jsx
> +const bigInt = require('big-integer');
Put on line above.

2022-05-28 13:22 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/components/Bridge.jsx
> -
Reinstate line break.

2022-05-28 13:22 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/components/Bridge.jsx
> +                  <button type="button" className="maxbuttons" onClick={() => this.maxDepositAmount(availableAmount)}>Max</button>
Have you tested this?

2022-05-28 16:13 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/components/Bridge.jsx
> +    this.setAmount = this.setAmount.bind(this);
Are you sure that you need this binding?

2022-05-28 17:44 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/components/Bridge.jsx
> +
Remove line break.

2022-05-28 22:17 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/components/Bridge.jsx
> +const bigInt = require('big-integer');
@koteakhaladze I said put on line above, not remove lines above. Third-party libraries are grouped together as per the comment.

2022-05-29 10:23 UTC, NeoXtreem requested changes
Have you actually tested your changes locally? There are still styling issues and what appears to be a major bug that will cause the values set by the buttons to not even work on the bridge.

1. Large border between the title and the top of the page (compared to the Farming page).
2. Width of textbox and SEND button too wide (compared to the Farming page).
3. Max placeholder shows an amount 18 orders of magnitude than the TS. The buttons also create such figures. This will fail on the bridge.

See comparison of Bridge and Farming page below (also shows bug 3 above).

![image](https://user-images.githubusercontent.com/16148007/170863271-4ffc267f-c83d-4575-978e-d74980a0ce11.png)
![image](https://user-images.githubusercontent.com/16148007/170863274-32d9b581-09bd-4890-b8fd-89757ee4956e.png)

2022-05-29 10:23 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/components/Bridge.jsx
> +  async updateAmount(e) {
@koteakhaladze Have you tested if this function is even called at runtime?

2022-05-29 11:30 UTC, koteakhaladze commented on SchnoodleDApp/ClientApp/src/components/Bridge.jsx
> +  async updateAmount(e) {
@NeoXtreem  yes this function works properly.

2022-05-29 23:12 UTC, NeoXtreem requested changes

2022-05-29 23:12 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/components/Bridge.jsx
> +  async updateAmount(e) {
@koteakhaladze Well, it does now that you removed the other same-named function in your [recent commit](https://github.com/schnoodledao/contracts/pull/12/commits/c306f41ae09392faec5f65d5ebf3ed8b0c3c400a). At the time you made this comment, it wasn't being called at all.

Also, why have you moved this function from its original location? It's now in an illogical place in the file.

2022-05-29 23:12 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/components/Bridge.jsx
> +  async setAmount(amount) {
Please position this function to be consistent with the Farming page.

2022-05-29 23:12 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/components/Bridge.jsx
> +    this.setState({amount: Math.min(Math.floor(value), scaleDownUnits(this.state.availableAmount))});
This now breaks DRY principle. Why not just call `setAmount` which already sets the state?

2022-05-29 23:14 UTC, NeoXtreem commented
> Have you actually tested your changes locally? There are still styling issues and what appears to be a major bug that will cause the values set by the buttons to not even work on the bridge.
> 
> 1. Large border between the title and the top of the page (compared to the Farming page).
> 2. Width of textbox and SEND button too wide (compared to the Farming page).
> 3. Max placeholder shows an amount 18 orders of magnitude than the TS. The buttons also create such figures. This will fail on the bridge.
> 
> See comparison of Bridge and Farming page below (also shows bug 3 above).
> 
> ![image](https://user-images.githubusercontent.com/16148007/170863271-4ffc267f-c83d-4575-978e-d74980a0ce11.png) ![image](https://user-images.githubusercontent.com/16148007/170863274-32d9b581-09bd-4890-b8fd-89757ee4956e.png)

@koteakhaladze Item 2 above is still an issue. Please fix.

2022-05-30 15:54 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/components/Bridge.jsx
> +    const { sourceNetwork, targetNetwork, selectedAddress, busySwap, busyReceive, tokensPending, fee, amount, serverStatus, serverError, message } = this.state;
@koteakhaladze Add line break after this line (as it was previously).

2022-05-30 15:56 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/components/Bridge.jsx
> +    console.log(amount);
Remove console log.

2022-05-30 15:57 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/components/Bridge.jsx
> +      valueContainer: () => ({ width: 100, border: 'none', display: 'grid'}),
Formatting (add space).

2022-05-30 15:58 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/components/Bridge.jsx
> +    const { Option, SingleValue } = components;
Add line break before.

2022-05-31 03:47 UTC, NeoXtreem approved these changes

2022-05-31 03:47 UTC, merged