dw-145/schnoodlev9-react-hooks
schnoodledao/contracts pull request #13
Opened 2022-06-03 13:21 UTC by koteakhaladze

2022-06-06 17:05 UTC, NeoXtreem requested changes
### General comments
- Add comma to all line endings of `interface` types to comply with ReSharper rules (I suggest installing this).
- There is a mix of 2-space and 4-space indenting throughout all your changes. Please be consistent.
- Don't remove EOF line feeds. Keep them there for now for consistency until we make a different decision on this.
- Use single quotes for all JavaScript strings, and double quotes for all HTML string.
- Ensure all statements end with a semicolon.

### Code lost from copy-pasting
I have spotted a number of inconsistencies in this PR versus changes I have made.

For example [here](https://github.com/schnoodledao/contracts/pull/13/files#diff-fffe4aa0ba4086cd8e04851b5dc9d8ada4ce2bea16af8564303946b2de0786f2R439), this was changed to say "Waiting for server" instead of "Server offline" in commit 675048.

And [here](https://github.com/schnoodledao/contracts/pull/13/files#diff-fffe4aa0ba4086cd8e04851b5dc9d8ada4ce2bea16af8564303946b2de0786f2R286), this should say `if (fee > 0)`, not `if (fee)`. I changed this in commit bd1c9f.

I suspect there are plenty more issues like this. It appears that you have copy-pasted code from your original branch under PR #9 without considering changes made since.

I therefore have difficult trusting this PR now. You will need to carefully go through every commit since that branch (from commit 7761c6), and ensure every change made since then is in the refactored code.

### Next steps
I would suggest you do the follow before we proceed further with this PR:
- Either manually ensure every single change made to the touched files since commit 7761c6 is incorporated into your changes, or close the PR and start again, and do not copy-paste code over code next time without exercising full due diligence on what your actual changes are.
- Due to the large change, and the amount of formatting issues, please install and configure eslint to eliminate formatting issues as this is taking up a lot of review time.

2022-06-08 00:23 UTC, NeoXtreem commented
@koteakhaladze Status?

2022-06-08 11:13 UTC, koteakhaladze commented on SchnoodleDApp/ClientApp/src/App.tsx
> +export default class App extends Component {
> @koteakhaladze Status?

pushed a commit.

2022-06-08 23:10 UTC, NeoXtreem commented
> ### General comments
> * Add comma to all line endings of `interface` types to comply with ReSharper rules (I suggest installing this).
> * There is a mix of 2-space and 4-space indenting throughout all your changes. Please be consistent.
> * Don't remove EOF line feeds. Keep them there for now for consistency until we make a different decision on this.
> * Use single quotes for all JavaScript strings, and double quotes for all HTML string.
> * Ensure all statements end with a semicolon.
> 
> ### Code lost from copy-pasting
> I have spotted a number of inconsistencies in this PR versus changes I have made.
> 
> For example [here](https://github.com/schnoodledao/contracts/pull/13/files#diff-fffe4aa0ba4086cd8e04851b5dc9d8ada4ce2bea16af8564303946b2de0786f2R439), this was changed to say "Waiting for server" instead of "Server offline" in commit [675048c](https://github.com/schnoodledao/contracts/commit/675048c9a5fad785e9877893c9c3d9f2f4dc3daa).
> 
> And [here](https://github.com/schnoodledao/contracts/pull/13/files#diff-fffe4aa0ba4086cd8e04851b5dc9d8ada4ce2bea16af8564303946b2de0786f2R286), this should say `if (fee > 0)`, not `if (fee)`. I changed this in commit [bd1c9f2](https://github.com/schnoodledao/contracts/commit/bd1c9f26f6b7c8de284737937e05227d683457e6).
> 
> I suspect there are plenty more issues like this. It appears that you have copy-pasted code from your original branch under PR #9 without considering changes made since.
> 
> I therefore have difficult trusting this PR now. You will need to carefully go through every commit since that branch (from commit [7761c6c](https://github.com/schnoodledao/contracts/commit/7761c6cc6e0b55b400e90141d7dc8d951e4cbd18)), and ensure every change made since then is in the refactored code.
> 
> ### Next steps
> I would suggest you do the follow before we proceed further with this PR:
> 
> * Either manually ensure every single change made to the touched files since commit [7761c6c](https://github.com/schnoodledao/contracts/commit/7761c6cc6e0b55b400e90141d7dc8d951e4cbd18) is incorporated into your changes, or close the PR and start again, and do not copy-paste code over code next time without exercising full due diligence on what your actual changes are.
> * Due to the large change, and the amount of formatting issues, please install and configure eslint to eliminate formatting issues as this is taking up a lot of review time.

@koteakhaladze Are you still working on ^this?

2022-06-13 22:22 UTC, NeoXtreem commented
@koteakhaladze I've had a look, and there's still a lot of code missing. I've done a few spot checks, and I'm finding missing code everywhere. For example:

- [These lines](https://github.com/schnoodledao/contracts/commit/44258afd6176cff6ef8c6024687a87cf9e25806e#diff-8f213d5da6ab5342f84b7da8c8b124146ebb8f0b9d6a15a6098982c396820ec9R260-R262) from commit 44258afd6176cff6ef8c6024687a87cf9e25806e on 22 May.
- [These lines](https://github.com/schnoodledao/contracts/commit/4b9a93174fe01763124aec62c8c1ff047e82bcce#diff-8f213d5da6ab5342f84b7da8c8b124146ebb8f0b9d6a15a6098982c396820ec9R68-R115) from commit 4b9a93174fe01763124aec62c8c1ff047e82bcce on 6 June.

I think the best thing to do might just be to take the latest Bridge.jsx and refactor it to React Hooks and TypeScript from scratch carefully using the code from your previous attempts, but bit by bit, line by line. No copy-pasting large chunks of code. This is causing lots of code to be lost.

Please fix.

2022-06-15 07:19 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/components/Bridge.tsx
> +  const updateWeb3 = async () => {
Why have you re-added this function? This was removed in commit 4b9a93174fe01763124aec62c8c1ff047e82bcce.

You agreed to redo Bridge.jsx from scratch based on the latest version (which was also indicated in your commit comment). If that was true, then you wouldn't have ended up with this function. I haven't checked the rest of the file because it is clear that you haven't done as we agreed.

Please fix again.

2022-06-16 21:52 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/components/Bridge.tsx
> +    name: 'Ethereum',
@koteakhaladze Dude, what's going on?!? I'm right at the top of the file, and again I'm seeing code lost! This line was changed in my commit cdcd84a1a8e9ad278ad53a54e446ab917996379c on 5 June.

Seriously, now, stop this. Stop copying your old code. Do it from scratch. If you keep copying old code, you will lose all my code. I've changed most of the code in Bridge.jsx since your first attempt.

If you can't handle doing it from scratch, then I will just put this to the community for a bounty.

2022-08-21 17:47 UTC, merged