dw-230/schnoodlev9-bridge-styling
schnoodledao/contracts pull request #14
Opened 2022-06-06 11:51 UTC by koteakhaladze

2022-06-06 14:28 UTC, NeoXtreem requested changes
See styling comments below...
![image](https://user-images.githubusercontent.com/16148007/172180997-8206c4af-497e-4083-b7ba-84e24f82c767.png)
![image](https://user-images.githubusercontent.com/16148007/172181394-cd306ee0-9aeb-4a56-9dcf-b95efecff5c1.png)

2022-06-06 14:28 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/components/Bridge.jsx
> +                  <div className="purplefade tw-opacity-50 tw-uppercase tw-text-xl tw-font-bold">{token}</div>
Thanks for fixing.

2022-06-06 14:28 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/components/Bridge.jsx
> +                  <span className="text-main-color tw-font-medium">{scaleDownUnits(tokensPending)}</span> <span className="tw-text-white tw-font-bold">{'SNOOD ready to be received'}</span>
Why have you reverted my change here?

2022-06-06 14:28 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/custom.css
> +.keybtnbridge {
Why are we duplicating CSS styles just for the bridge? Why not use existing styles to ensure common look and feel across the application? Also, more DRY.

2022-06-06 14:28 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/custom.css
> +.maxbuttonbridge {
Why are we duplicating CSS styles just for the bridge? Why not use existing styles to ensure common look and feel across the application? Also, more DRY.

2022-06-07 15:00 UTC, koteakhaladze commented on SchnoodleDApp/ClientApp/src/components/Bridge.jsx
> +                  <span className="text-main-color tw-font-medium">{scaleDownUnits(tokensPending)}</span> <span className="tw-text-white tw-font-bold">{'SNOOD ready to be received'}</span>
put the old code back.

2022-06-07 15:01 UTC, koteakhaladze commented on SchnoodleDApp/ClientApp/src/custom.css
> +.keybtnbridge {
fixed. added a new css style according to DRY.

2022-06-08 00:12 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/custom.css
> +.maxbuttonbridge {
@koteakhaladze Can you please address this?

2022-06-08 00:19 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/custom.css
> +.keybtnbridge {
What about the `maxbuttonbridge` style? If the MAX button is identical to the Farming page MAX button, then surely the same style can be used?...

2022-06-08 00:21 UTC, NeoXtreem commented
> See styling comments below... ![image](https://user-images.githubusercontent.com/16148007/172180997-8206c4af-497e-4083-b7ba-84e24f82c767.png) ![image](https://user-images.githubusercontent.com/16148007/172181394-cd306ee0-9aeb-4a56-9dcf-b95efecff5c1.png)

@koteakhaladze The RECEIVE button is still pink. And the swap button should also use the same Farming styling. I said previously that we should not use any of the old pink-based styling from B&R Group, but use our own styling as used in the Farming page (where there's no pink).

2022-06-08 11:03 UTC, koteakhaladze commented on SchnoodleDApp/ClientApp/src/custom.css
> +.maxbuttonbridge {
@neoxtreem yes, I will recheck this. but pixel wise this modification makes it perfectly matched in the bridge page.

2022-06-09 23:31 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/custom.css
> +.maxbuttonbridge {
@koteakhaladze Can you explain what you mean? The pixels should match exactly. It's a text box and button in both the Farming and Bridge pages.

2022-06-10 01:32 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/components/Bridge.jsx
> +                <button type="button" onClick={this.receiveTokens} className="tw-w-1/2 keybtn maxbuttons">{networks[targetNetwork].id === networkId ? 'RECEIVE' : 'SWITCH NETWORK'}</button>
Is it not more consistent for `maxbuttons` to be renamed to `maxbtn` in the CSS file? Perhaps other button styles should also be renamed like this?...

2022-06-10 01:33 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/components/Bridge.jsx
> -        <img src="/assets/img/svg/load.svg" alt="" className="tw-w-16 tw-h-16 tw-mb-8 lg:tw-mb-11 tw-animate-spin" />
Asset still needed?

2022-06-10 20:46 UTC, koteakhaladze commented on SchnoodleDApp/ClientApp/src/custom.css
> +.maxbuttonbridge {
<img width="460" alt="Screenshot 2022-06-11 at 00 43 08" src="https://user-images.githubusercontent.com/53879171/173147490-20b5b46a-9fc1-40c6-a4bf-ffd363ae6720.png">
<img width="497" alt="Screenshot 2022-06-11 at 00 43 52" src="https://user-images.githubusercontent.com/53879171/173147503-cbd902b0-0082-47fc-aa24-8069ff359b7d.png">

in farming page we have an input and buttons for unbonding blocks with 0 left margin and a deposit button with left margin which makes it not aligned. I was trying to avoid it in the bridge page. but we can leave as it is for now.

2022-06-10 20:47 UTC, koteakhaladze commented on SchnoodleDApp/ClientApp/src/components/Bridge.jsx
> +                <button type="button" onClick={this.receiveTokens} className="tw-w-1/2 keybtn maxbuttons">{networks[targetNetwork].id === networkId ? 'RECEIVE' : 'SWITCH NETWORK'}</button>
Ok, agreed.

2022-06-10 20:48 UTC, koteakhaladze commented on SchnoodleDApp/ClientApp/src/components/Bridge.jsx
> -        <img src="/assets/img/svg/load.svg" alt="" className="tw-w-16 tw-h-16 tw-mb-8 lg:tw-mb-11 tw-animate-spin" />
No, will delete in the next commit.

2022-06-12 00:55 UTC, NeoXtreem approved these changes

2022-06-12 00:55 UTC, merged