Add Uniswap widget
schnoodledao/contracts pull request #15
Opened 2022-07-04 17:11 UTC by tnrdd

Add the Uniswap widget to the Home component of the frontend

2022-07-08 20:43 UTC, NeoXtreem requested changes
Solution is good overall, but I think it might be overkill to put it in a separate component. It might be better to put it in line with the `Home` component like in PR #16 (which was done after yours, so yours wins 😉) as the component is only being used once. If it were being used in multiple places, then it might warrant being its own component.

2022-07-08 20:43 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/components/UniswapWidget.jsx
> +          defaultInputAmount={1}
A value of 1 is a bit arbitrary. Any reason for the choice?

2022-07-08 20:43 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/components/UniswapWidget.jsx
> +        <SwapWidget
Might be worth adding `defaultInputTokenAddress={NATIVE}` to this.

2022-07-08 20:43 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/components/UniswapWidget.jsx
> +  1: 'https://tokens.coingecko.com/uniswap/all.json',
If the default token list is used as per [here](https://docs.uniswap.org/sdk/widgets/swap-widget#customizing-token-lists), doesn't the user have the option of selecting a list from a list of lists as per the official Uniswap app?

2022-07-09 05:40 UTC, tnrdd commented on SchnoodleDApp/ClientApp/src/components/UniswapWidget.jsx
> +};
The widget doesn't let you import tokens manually like the full app.
If a list is not included the default one from Uniswap is be used, but SNOOD is not present, would using another token from the list be enough for testing purpose?

2022-07-09 05:42 UTC, tnrdd commented on SchnoodleDApp/ClientApp/src/components/UniswapWidget.jsx
> +        'https://assets.coingecko.com/coins/images/17458/thumb/r    c8zDq3.png?1654497345',
Yes must have accidentally hit the keyboard before committing

2022-07-09 05:47 UTC, tnrdd commented on SchnoodleDApp/ClientApp/src/components/UniswapWidget.jsx
> +  success: '#8a5af5',
Absolutely, this is the ![widget](https://user-images.githubusercontent.com/41868860/178093338-6313361a-2235-4383-ae40-3e944fb79da3.png) `darkTheme` extended with the buttons using the RGB values from the CSS.
Is this similar with what you had in mind?

2022-07-09 05:49 UTC, tnrdd commented on SchnoodleDApp/ClientApp/src/components/UniswapWidget.jsx
> +          defaultInputAmount={1}
Just because it's a nice whole number but no strong reason.
The prop is optional, should we omit so that the default input amount is 0?

2022-07-09 05:50 UTC, tnrdd commented on SchnoodleDApp/ClientApp/src/components/UniswapWidget.jsx
> +  1: 'https://tokens.coingecko.com/uniswap/all.json',
Unfortunately the widget doesn't let you manage token lists like the app.

2022-08-25 07:40 UTC, merged